### ISSUE TITLE
.

### ISSUE THREAD

**Issue by aa1008611** [SalaRNd/MTProto-Proxy-Easy-Installer#1]
配置文件 在哪里
可以更改英文版的嘛 波斯语看不懂

**Comment by SalaRNd** [comment]
Hello
I will add the English language soon

**Comment by aa1008611** [comment]
这个 在中国 流量被识别 封端口



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月11日 23:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [SalaRNd/MTProto-Proxy-Easy-Installer] 编辑配置文件是哪个 (Issue #1) |

Hello
I will add the English language soon
